// Regenerates web/src/lib/abis.ts from the compiled forge artifacts.
// C1 makes the Solidity ABI the source of truth; this file keeps the frontend a projection of
// it rather than a second, drifting copy. Run `forge build` in contracts/ first.
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const artifact = (name) => {
  const p = path.join(root, 'contracts', 'out', `${name}.sol`, `${name}.json`)
  if (!fs.existsSync(p)) {
    console.error(`missing ${p}\nrun: cd contracts && forge build`)
    process.exit(1)
  }
  return JSON.parse(fs.readFileSync(p, 'utf8')).abi
}

const out =
  '// GENERATED by `npm run gen:abi` from contracts/out. Never hand-edited.\n' +
  '// C1: the Solidity ABI is the source of truth and this file is a projection of it.\n\n' +
  `export const escrowAbi = ${JSON.stringify(artifact('Escrow'), null, 2)} as const\n\n` +
  `export const escrowFactoryAbi = ${JSON.stringify(artifact('EscrowFactory'), null, 2)} as const\n`

fs.writeFileSync(path.join(root, 'web', 'src', 'lib', 'abis.ts'), out)
console.log('wrote web/src/lib/abis.ts')
